name: Quality And Tests

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:

  CodeQuality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lint
      run: docker-compose run --entrypoint="./run-lint.sh" app

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: code-quality-artifact
        path: pkg/tests/outputs/output_lint.log
      
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: docker-compose run --entrypoint="./run-tests.sh" app
    
    - uses: actions/upload-artifact@v2
      with:
        name: tests-artifact
        path: pkg/tests/coverage/coverage.html

